# These are supported funding model platforms

github: ['whiskeysockets', 'nodejs', 'KazeDevID', 'kazedepid'] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://whatsapp.com/channel/0029VaFNnRTHLHQR6G0fC01O'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
